### PR TITLE
Updating for latest YouTrack

### PR DESCRIPTION
**Pull request by mhedgpeth**
We used your cookbook for our migration to Chef on CentOS 7 and YouTrack 6.X. we had to make some changes to get it to work and wanted to merge those with your so the community will benefit.

### CODE REVIEW

**Comment by vslinko** [comment]
First of all thank you for pull request.

But as you can see in organisation name this repository is archived.
That means I can't merge your PR.

But I can transfer this repo to your github account if you want to maintain it.

**Comment by mhedgpeth** [comment]
I would love to own the repo. Could you also migrate the ownership on the chef supermarket to me as well? My user id there is mhedgpeth.

**Comment by vslinko** [comment]
Chef Supermarket transfer request sent.

To transfer github repo you should remove your fork from your github account.
You could save a copy with PR on your localhost.

**Comment by mhedgpeth** [comment]
I finished deleting the repository on github so we're ready.

**Comment by vslinko** [comment]
Request sent

**Comment by vslinko** [comment]
Good luck to you! :smile: :+1:

**Comment by mhedgpeth** [comment]
Got it. Thanks for your help!

**Pull request closed without merging**
